--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Verre2OuiSki/SayWelcome
build-by-default: true
branches:
- main
projects:
  CapesLocker:
    path: ""
    icon: ./meta/icon.png
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
...